### ISSUE TITLE
Broken imports

### ISSUE THREAD

**Issue by jaroslav-muller** [tatumio/tatum-js#160]
Running a basic example
```
const { generateWallet, Currency } = require('@tatumio/tatum');
const btcWallet = generateWallet(Currency.BTC, true);
console.log(btcWallet);
```
throws:
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'src/blockchain'
Require stack:
- /home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/transaction/algo.js
- /home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/transaction/index.js
- /home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/helpers/index.js
- /home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/fungible/index.js
- /home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/wallet/custodial.js
- /home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/wallet/index.js
- /home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/index.js
- /home/jarin/dev/probinex/exp/tatum/test.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/transaction/algo.js:6:22)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/jarin/dev/probinex/exp/tatum/node_modules/@tatumio/tatum/dist/src/transaction/index.js:34:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
```

_Originally posted by @jaroslav-muller in https://github.com/tatumio/tatum-js/pull/157#r713006035_

**Comment by samuelsramko** [comment]
fixing in this pipeline - https://github.com/tatumio/tatum-js/actions/runs/1257672914
