### ISSUE TITLE
bitcoin -> offchain (sendBitcoinOffchainTransaction) errors

### ISSUE THREAD

**Issue by contra** [tatumio/tatum-js#70]
Blows up here: https://github.com/tatumio/tatum-js/blob/master/src/offchain/bitcoin.ts#L95

```
Error: Invalid Argument: First argument is required, please include address data. Documentation: http://bitcore.io/guide/address.html
Error
    at new NodeError (/Users/contra/Projects/createsafe-wallet/api/node_modules/bitcore-lib/lib/errors/index.js:20:41)
    at Object.checkArgument (/Users/contra/Projects/createsafe-wallet/api/node_modules/bitcore-lib/lib/util/preconditions.js:14:13)
    at new Address (/Users/contra/Projects/createsafe-wallet/api/node_modules/bitcore-lib/lib/address.js:69:5)
    at Address (/Users/contra/Projects/createsafe-wallet/api/node_modules/bitcore-lib/lib/address.js:57:12)
    at Function.Script.fromAddress (/Users/contra/Projects/createsafe-wallet/api/node_modules/bitcore-lib/lib/script/script.js:1010:13)
    at /Users/contra/Projects/createsafe-wallet/api/node_modules/@tatumio/tatum/src/offchain/bitcoin.ts:95:36
    at Array.forEach (<anonymous>)
    at Object.prepareBitcoinSignedOffchainTransaction (/Users/contra/Projects/createsafe-wallet/api/node_modules/@tatumio/tatum/src/offchain/bitcoin.ts:90:14)
    at Object.sendBitcoinOffchainTransaction (/Users/contra/Projects/createsafe-wallet/api/node_modules/@tatumio/tatum/src/offchain/bitcoin.ts:30:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I think this is an API issue, the API `WithdrawalResponseData[]` response has a null address:

![Screen Shot 2021-06-20 at 4 25 15 PM](https://user-images.githubusercontent.com/425716/122691423-6f00bc80-d1e4-11eb-9676-eadc1a047560.png)

And in this function there doesn't seem to be any behavior defined for this case, which leads me to think the API is at fault. Transferring with the same code/account/ledger works fine with other currencies besides BTC.

**Comment by samuelsramko** [comment]
This is definitely an API issue. We will investigate.

**Comment by samuelsramko** [comment]
@contra I have found a problem. Problem is, that you are combining two approaches in BTC offchain - you are assigning addresses manually to the ledger accounts without using xpubs, but you don't provide attr field in the sendBtcOffchain method. If you want to use manual addresses, you need to set attr field to the change address of your wallet. If you don't do that, your data will be wrong. Please take a look here - https://tatum.io/apidoc#operation/BtcTransfer

**Comment by contra** [comment]
@samuelsramko Using `attr` the first call every few hours works and the transaction is recorded, but any transaction after that fails with the same error as above ^ Not sure why it would be inconsistent like that - the only thing I can think of is the API results are coming back different intermittently.

I tried going the xpub route when making the accounts, but the addresses for the deposit addresses didn't match up with the output we expected from `generateAddressFromXPub` - could you clarify which derivationKey is used when tatum generates a deposit address from an xpub?

**Comment by samuelsramko** [comment]
Your address in attr cant be LinkedIn to ledger account and being watched. It must be your change address outside of the ledger account. When you generate address from the xpub, you always get index of that address. First used index is 1 for every xpub.

**Comment by contra** [comment]
@samuelsramko Thanks for the info - using the xpub on account create has resolved it for us. I think some additional docs around this and better error messaging might be useful for future people (if address in the API === null, throw an error in the SDK with info instead of letting the lower level libs blow up)
